version: 2
updates:
  - package-ecosystem: "pip" # Specifies Python's package manager
    directory: "/" # Adjust if your requirements file is in a subdirectory
    schedule:
      interval: "weekly"
